# Generated by Django 4.1.3 on 2022-11-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_remove_profile_id_alter_profile_profilepicture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(default='profilepictures/default.png', upload_to='profilepictures'),
        ),
    ]
