# Generated by Django 4.1.2 on 2022-11-23 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=upload.models.create_path)),
                ('file_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('urltoken', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
